parameters:
- name: Environment
  displayName: 'Select an environment'
  type: string
  default: 'development'
  values:
    - 'development'
    - 'production'

trigger:
- main

variables:
- ${{ if eq(parameters.Environment, 'development') }}:
  - group: firebase_dev
- ${{ if eq(parameters.Environment, 'production') }}:
  - group: firebase_prod

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.17.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g firebase-tools
    npm install
  displayName: 'NPM Install dependencies'

- script: |
    echo '$(FIREBASE_SERVICE_ACCOUNT_KEY)' > key.json
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/key.json
    npm run import_runtime:$(APP_ENV)
  displayName: 'GET runtimeconfig'

- script: |
    echo '$(FIREBASE_SERVICE_ACCOUNT_KEY)' > key.json
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/key.json
    npm run deploy:$(APP_ENV)
  displayName: 'Deploy on firebase ${{ parameters.Environment }}'
