trigger:
- main

variables:
- group: firebase_dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.17.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g firebase-tools
    npm install
  displayName: 'NPM Install dependecies'
  
- script: |
    firebase experiments:enable webframeworks
  displayName: 'enabling firebase experiments'

- script: |
    echo '$(FIREBASE_SERVICE_ACCOUNT_KEY)' > key.json
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/key.json
  displayName: 'Setup project Firebase'

- script: |
    npm run import-runtime:$(APP_ENV)
  displayName: 'GET runtimeconfig'


- script: |
    npm run deploy:$(APP_ENV)
  displayName: 'deploy on $(APP_ENV) firebase'
